pub const ERR_INVALID_AMOUNT: felt252 = 'INVALID_AMOUNT';
pub const ERR_TREE_FULL: felt252 = 'TREE_FULL';
pub const ERR_NULLIFIER_SPENT: felt252 = 'NULLIFIER_SPENT';
pub const ERR_UNAUTHORIZED: felt252 = 'UNAUTHORIZED';
pub const ERR_TOKEN_TRANSFER: felt252 = 'TOKEN_TRANSFER_FAILED';
